#!/bin/sh

old_stash=$(git rev-parse -q --verify refs/stash)
# stash any unstaged or untracked changes
git stash -q --keep-index --include-untracked
new_stash=$(git rev-parse -q --verify refs/stash)

# If there were no changes (e.g., `--amend` or `--allow-empty`)
# then nothing was stashed, and we should skip everything,
# including the tests themselves.  (Presumably the tests passed
# on the previous commit, so there is no need to re-run them.)
if [ "$old_stash" = "$new_stash" ]; then
    echo "pre-commit script: no changes"
    sleep 1 # XXX hack, editor may erase message
    exit 0
fi
# run the tests with the gradle wrapper
./gradlew check

# store the last exit code in a variable
RESULT=$?

# unstash the unstashed changes
# git reset --hard -q && git stash pop -q
git reset --hard -q && git stash apply --index -q && git stash drop -q

# return the './gradlew test' exit code
exit $RESULT
